http.sslbackend=openssl
http.sslcainfo=C:/Users/zcn3/AppData/Local/Programs/Git/mingw64/ssl/certs/ca-bundle.crt
credential.helper=manager-core
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
core.editor="C:\Users\zcn3\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait
user.email=adrianosturaro@yahoo.com.br
user.name=adrianosturaro
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
